apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: broadcasts.crddemo.joyrex2001.com
spec:
  group: crddemo.joyrex2001.com
  scope: Namespaced
  names:
    kind: Broadcast
    plural: broadcasts 
    singular: broadcast
    shortNames:
    - brc
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              message:
                type: string
              color:
                type: string